### ISSUE TITLE
Uncaught Error: Extension context invalidated

### ISSUE THREAD

**Issue by Kwonkunkun** [koba04/swr-devtools#120]
### problem
I try swr devtool extension but, occur the error and show white screen

```
content.ts:20 Uncaught Error: Extension context invalidated.
    at a (content.ts:20:13)
    at content.ts:49:18
```

and sometime show proper screen but not showing query history.

### env
```
swr: 2.1.0
next: 13.2.4 
```

I try erase and install all chrom extension
but not work 😢

**Comment by Kwonkunkun** [comment]
**"sometime show proper screen but not work" image**
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/59603575/225544509-b4af2194-75e6-4e2a-bdf5-0824176e5b04.png">


**"white screen" image**
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/59603575/225545025-cf50f42e-3446-4101-b136-fdab62fb3960.png">

**Comment by everythinginjs** [comment]
same here but confirm that it is working on FireFox.

**Comment by everythinginjs** [comment]
@Kwonkunkun  after checking #123  I used system theme and the problem fixed.

**Comment by koba04** [comment]
Thank you!

>  I used system theme and the problem fixed.

Yeah, that's a workaround 👍  I'll try to fix the root cause of the problem.
