### ISSUE TITLE
Support SSR

### ISSUE THREAD

**Issue by sculove** [koba04/swr-devtools#86]
I face the following message
```
error - ReferenceError: window is not defined
    at /Users/user/workspace/loan-web/node_modules/swr-devtools/src/createSWRDevTools.ts:88:5
    at Map.cache.set (/Users/user/workspace/loan-web/node_modules/swr-devtools/src/swr-cache.ts:23:7)
```

You need to support the ssr!
Can you fix it?

**Comment by koba04** [comment]
@sculove 
Thank you for your feedback!
What versions of SWR and SWRDevTools do you use?
Do you add <SWRDevTools> into your application?

**Comment by sculove** [comment]
- SWR: 1.3.0
- SWRDevTools: 1.0.0

I saw the history of SSR-related issues resolved in the v1.1.1 release
However, in npm, only version 1.0.0 was available.

this is my application codes
```tsx
 <SWRDevTools>
    <SSRSWRConfig fallback={fallback} value={{fetcher: getClientAxios()}}>
        <RecoilRoot
            initializeState={({set}) => {
                set(loanUserState, {
                    type,
                    loanPathType,
                })
            }}>
            <UserAgentProvider userAgent={userAgent}>
                <AlertProvider>
                    <RenderByEnv Component={Component} pageProps={pageProps} />
                </AlertProvider>
                <GlobalErrorContainer />
            </UserAgentProvider>
        </RecoilRoot>
    </SSRSWRConfig>
</SWRDevTools>
```
